parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Optime\Acl\Bundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/OptimeAclBundle.php'

  Optime\Acl\Bundle\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  Optime\Acl\Bundle\Security\User\DefaultRolesProvider:
    arguments:
      - ""
      - '%security.role_hierarchy.roles%'

  Optime\Acl\Bundle\EventListener\SecurityListener:
    arguments:
      $enabledAuth: "%optime_acl.enabled%"

  Optime\Acl\Bundle\Security\Voter\ResourceVoter:
    arguments:
      $enabled: "%optime_acl.enabled%"
      $cacheResults: "%optime_acl.cache_voters%"

  Optime\Acl\Bundle\Security\Voter\ResourceRouteVoter:
    arguments:
      $enabled: "%optime_acl.enabled%"
      $cacheResults: "%optime_acl.cache_voters%"

  Optime\Acl\Bundle\Security\Voter\ResourceReferenceVoter:
    arguments:
      $enabled: "%optime_acl.enabled%"
      $cacheResults: "%optime_acl.cache_voters%"